// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.6
// Project name: Smart_Gadget

#ifndef _SMART_GADGET_UI_H
#define _SMART_GADGET_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "components/ui_comp.h"
#include "components/ui_comp_hook.h"
#include "ui_events.h"


void Up_Animation(lv_obj_t * TargetObject, int delay);
void hour_Animation(lv_obj_t * TargetObject, int delay);
void min_Animation(lv_obj_t * TargetObject, int delay);
void sec_Animation(lv_obj_t * TargetObject, int delay);
void scrolldot_Animation(lv_obj_t * TargetObject, int delay);
// SCREEN: ui_Splash
void ui_Splash_screen_init(void);
void ui_event_Splash(lv_event_t * e);
extern lv_obj_t * ui_Splash;
extern lv_obj_t * ui_SLS_Logo;
// SCREEN: ui_Clock
void updateTime(char hour[2], char min[2]);
void ui_Clock_screen_init(void);
void ui_event_Clock(lv_event_t * e);
extern lv_obj_t * ui_Clock;
extern lv_obj_t * ui_Clock_Number;
extern lv_obj_t * ui_Date;
extern lv_obj_t * ui_Weather_Icons2;
extern lv_obj_t * ui_w7;
extern lv_obj_t * ui_W1_Num2;
// SCREEN: ui_Alarm
void ui_Alarm_screen_init(void);
void ui_event_Alarm(lv_event_t * e);
extern lv_obj_t * ui_Alarm;
extern lv_obj_t * ui_Alarm_container;
extern lv_obj_t * ui_Set_alarm;
extern lv_obj_t * ui_Container1;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Roller1;
extern lv_obj_t * ui_Switch2;
extern lv_obj_t * ui_Checkbox2;
extern lv_obj_t * ui_Roller2;
extern lv_obj_t * ui____initial_actions0;


LV_IMG_DECLARE(ui_img_white_moved_sandclock_to_the_right_80_png);    // assets/white moved sandclock to the right 80.png
LV_IMG_DECLARE(ui_img_fon_png);    // assets/fon.png
LV_IMG_DECLARE(ui_img_weather_1_png);    // assets/weather_1.png



LV_FONT_DECLARE(ui_font_Number);



void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
