// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: Wecker

#include "ui.h"

void ui_Alarm_screen_init(void)
{
    ui_Alarm = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Alarm, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Bckg2 = lv_img_create(ui_Alarm);
    lv_img_set_src(ui_Bckg2, &ui_img_1_png);
    lv_obj_set_width(ui_Bckg2, LV_SIZE_CONTENT);   /// 320
    lv_obj_set_height(ui_Bckg2, LV_SIZE_CONTENT);    /// 240
    lv_obj_set_align(ui_Bckg2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Bckg2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Bckg2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Wecker = lv_label_create(ui_Alarm);
    lv_obj_set_width(ui_Wecker, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Wecker, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Wecker, 0);
    lv_obj_set_y(ui_Wecker, -96);
    lv_obj_set_align(ui_Wecker, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Wecker, "Wecker");
    lv_obj_set_style_text_font(ui_Wecker, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WeckerSetup = lv_obj_create(ui_Alarm);
    lv_obj_remove_style_all(ui_WeckerSetup);
    lv_obj_set_width(ui_WeckerSetup, 308);
    lv_obj_set_height(ui_WeckerSetup, 123);
    lv_obj_set_x(ui_WeckerSetup, 1);
    lv_obj_set_y(ui_WeckerSetup, 11);
    lv_obj_set_align(ui_WeckerSetup, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_WeckerSetup, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_HourRoller = lv_roller_create(ui_WeckerSetup);
    lv_roller_set_options(ui_HourRoller,
                          "00\n01\n02\n03\n04\n05\n06\n07\n08\n09\n10\n11\n12\n13\n14\n15\n16\n17\n18\n19\n20\n21\n22\n23",
                          LV_ROLLER_MODE_NORMAL);
    lv_obj_set_height(ui_HourRoller, 100);
    lv_obj_set_width(ui_HourRoller, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_HourRoller, -85);
    lv_obj_set_y(ui_HourRoller, 0);
    lv_obj_set_align(ui_HourRoller, LV_ALIGN_CENTER);
    lv_obj_set_style_text_font(ui_HourRoller, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_HourRoller, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_HourRoller, lv_color_hex(0xE9E9E9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_HourRoller, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_HourRoller, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_HourRoller, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_HourRoller, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(ui_HourRoller, lv_color_hex(0x000000), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_HourRoller, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_HourRoller, LV_TEXT_ALIGN_AUTO, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_HourRoller, 100, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_HourRoller, lv_color_hex(0xDADADA), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_HourRoller, 200, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_Colon = lv_label_create(ui_WeckerSetup);
    lv_obj_set_width(ui_Colon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Colon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Colon, -35);
    lv_obj_set_y(ui_Colon, 0);
    lv_obj_set_align(ui_Colon, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Colon, ":");
    lv_obj_set_style_text_font(ui_Colon, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MinRoller = lv_roller_create(ui_WeckerSetup);
    lv_roller_set_options(ui_MinRoller,
                          "00\n01\n02\n03\n04\n05\n06\n07\n08\n09\n10\n11\n12\n13\n14\n15\n16\n17\n18\n19\n20\n21\n22\n23",
                          LV_ROLLER_MODE_NORMAL);
    lv_obj_set_height(ui_MinRoller, 100);
    lv_obj_set_width(ui_MinRoller, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_MinRoller, 15);
    lv_obj_set_y(ui_MinRoller, 0);
    lv_obj_set_align(ui_MinRoller, LV_ALIGN_CENTER);
    lv_obj_set_style_text_font(ui_MinRoller, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_MinRoller, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_MinRoller, lv_color_hex(0xE9E9E9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MinRoller, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_MinRoller, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_MinRoller, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_MinRoller, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(ui_MinRoller, lv_color_hex(0x000000), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MinRoller, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_MinRoller, LV_TEXT_ALIGN_AUTO, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_MinRoller, 100, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_MinRoller, lv_color_hex(0xDADADA), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MinRoller, 200, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_EnableAlarm = lv_switch_create(ui_WeckerSetup);
    lv_obj_set_width(ui_EnableAlarm, 50);
    lv_obj_set_height(ui_EnableAlarm, 25);
    lv_obj_set_x(ui_EnableAlarm, 105);
    lv_obj_set_y(ui_EnableAlarm, -20);
    lv_obj_set_align(ui_EnableAlarm, LV_ALIGN_CENTER);

    lv_obj_set_style_bg_color(ui_EnableAlarm, lv_color_hex(0xDFDFDF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_EnableAlarm, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_EnableAlarm, lv_color_hex(0xA0A1DD), LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_EnableAlarm, 255, LV_PART_INDICATOR | LV_STATE_CHECKED);

    lv_obj_set_style_bg_color(ui_EnableAlarm, lv_color_hex(0x5F5F5F), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_EnableAlarm, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_EnableAlarm, lv_color_hex(0x5F5F5F), LV_PART_KNOB | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_EnableAlarm, 255, LV_PART_KNOB | LV_STATE_CHECKED);

    ui_Snooze = lv_checkbox_create(ui_WeckerSetup);
    lv_checkbox_set_text(ui_Snooze, "Snooze");
    lv_obj_set_width(ui_Snooze, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Snooze, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Snooze, 109);
    lv_obj_set_y(ui_Snooze, 27);
    lv_obj_set_align(ui_Snooze, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Snooze, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    lv_obj_set_style_bg_color(ui_Snooze, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Snooze, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Snooze, lv_color_hex(0x000000), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Snooze, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Snooze, 1, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Snooze, lv_color_hex(0xA0A1DD), LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_Snooze, 255, LV_PART_INDICATOR | LV_STATE_CHECKED);

    lv_obj_add_event_cb(ui_Alarm, ui_event_Alarm, LV_EVENT_ALL, NULL);

}
