// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: Wecker

#include "ui.h"

void ui_Splash_screen_init(void)
{
    ui_Splash = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Splash, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Splash, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Splash, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Splash, lv_color_hex(0xFFFFFF), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Splash, 255, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_Logo = lv_img_create(ui_Splash);
    lv_img_set_src(ui_Logo, &ui_img_1386888695);
    lv_obj_set_width(ui_Logo, LV_SIZE_CONTENT);   /// 320
    lv_obj_set_height(ui_Logo, LV_SIZE_CONTENT);    /// 290
    lv_obj_set_x(ui_Logo, -1);
    lv_obj_set_y(ui_Logo, -26);
    lv_obj_set_align(ui_Logo, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Logo, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Logo, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_FETA = lv_label_create(ui_Splash);
    lv_obj_set_width(ui_FETA, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_FETA, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_FETA, 0);
    lv_obj_set_y(ui_FETA, 74);
    lv_obj_set_align(ui_FETA, LV_ALIGN_CENTER);
    lv_label_set_text(ui_FETA, "FETA");
    lv_obj_set_style_text_letter_space(ui_FETA, 7, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_FETA, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_FETA, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_FetaText = lv_label_create(ui_Splash);
    lv_obj_set_width(ui_FetaText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_FetaText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_FetaText, 0);
    lv_obj_set_y(ui_FetaText, 98);
    lv_obj_set_align(ui_FetaText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_FetaText, "FERTIGUNGS EINHEIT TECHNISCHER AUFGABEN");
    lv_obj_set_style_text_decor(ui_FetaText, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_FetaText, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Splash, ui_event_Splash, LV_EVENT_ALL, NULL);

}
