// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.6
// Project name: Smart_Gadget

#include "../ui.h"


void updateTime(char hour[2], char min[2]){

    ui_Clock_Number = lv_label_create(ui_Clock);
    lv_obj_set_width(ui_Clock_Number, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Clock_Number, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Clock_Number, 0);
    lv_obj_set_y(ui_Clock_Number, 96);
    lv_obj_set_align(ui_Clock_Number, LV_ALIGN_TOP_MID);

    char time[6] = {hour[0],hour[1], ':', min[0],min[1]};

    lv_label_set_text(ui_Clock_Number, time);
    lv_obj_set_style_text_color(ui_Clock_Number, lv_color_hex(0x191B18), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Clock_Number, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_Clock_Number, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_Clock_Number, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Clock_Number, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Clock_Number, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Clock_Number, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Clock_Number, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Clock_Number, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
}

void ui_Clock_screen_init(void)
{
    ui_Clock = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Clock, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_Clock, &ui_img_fon_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_tiled(ui_Clock, true, LV_PART_MAIN | LV_STATE_DEFAULT);

    updateTime("00","00");

    ui_Date = ui_Small_Label_create(ui_Clock);
    lv_obj_set_x(ui_Date, 2);
    lv_obj_set_y(ui_Date, 153);
    lv_label_set_text(ui_Date, "Mon 28 Oct");
    lv_obj_set_style_text_color(ui_Date, lv_color_hex(0x545454), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Date, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Weather_Icons2 = lv_obj_create(ui_Clock);
    lv_obj_set_height(ui_Weather_Icons2, 56);
    lv_obj_set_width(ui_Weather_Icons2, lv_pct(37));
    lv_obj_set_x(ui_Weather_Icons2, 120);
    lv_obj_set_y(ui_Weather_Icons2, -160);
    lv_obj_set_align(ui_Weather_Icons2, LV_ALIGN_BOTTOM_MID);
    lv_obj_clear_flag(ui_Weather_Icons2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Weather_Icons2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Weather_Icons2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_w7 = lv_img_create(ui_Weather_Icons2);
    lv_img_set_src(ui_w7, &ui_img_weather_1_png);
    lv_obj_set_width(ui_w7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_w7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_w7, 43);
    lv_obj_set_y(ui_w7, 0);
    lv_obj_add_flag(ui_w7, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_w7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_img_recolor(ui_w7, lv_color_hex(0x293062), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(ui_w7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_W1_Num2 = ui_Small_Label_create(ui_Weather_Icons2);
    lv_obj_set_x(ui_W1_Num2, 35);
    lv_obj_set_y(ui_W1_Num2, 25);
    lv_obj_set_align(ui_W1_Num2, LV_ALIGN_TOP_LEFT);
    lv_label_set_text(ui_W1_Num2, "65%");

    lv_obj_add_event_cb(ui_Clock, ui_event_Clock, LV_EVENT_ALL, NULL);

}
